
INSERT into epa_la_base2.usuarios (nombre,apellido,email,password,foto)

VALUES("Marciano","Visitante","marcianovisitante@neptuno.com","$2a$10$cj6AdR3sLeyH3RHErziXHOrWGeNjxz8QZ.dVxzziMXyLcS32VuCqS","vitruvio.jpg"),
("ET","Original","etoriginal@saturno.com","$2a$10$cj6AdR3sLeyH3RHErziXHOrWGeNjxz8QZ.dVxzziMXyLcS32VuCqS","foto-1656475673864.jpeg");

INSERT into epa_la_base2.usuarios (nombre,apellido,email,isAdmin,password,foto)
VALUES("Tony","González","gonzalezantonio@digitalhouse.com",1,"$2a$10$cj6AdR3sLeyH3RHErziXHOrWGeNjxz8QZ.dVxzziMXyLcS32VuCqS","vitruvio.jpg"),
("Fran","Spinelli","franco.spinelli@digitalhouse.com",1,"$2a$10$cj6AdR3sLeyH3RHErziXHOrWGeNjxz8QZ.dVxzziMXyLcS32VuCqS","vitruvio.jpg"),
("Ivan","Laipa","ivan@epa-la-ipa.tom.ar",1,"$2a$10$cj6AdR3sLeyH3RHErziXHOrWGeNjxz8QZ.dVxzziMXyLcS32VuCqS","alien3.jpg"),
("Seba","Laipa","seba@epa-la-ipa.tom.ar",1,"$2a$10$cj6AdR3sLeyH3RHErziXHOrWGeNjxz8QZ.dVxzziMXyLcS32VuCqS","alien1.jpg"),
("Lean","Laipa","lean@epa-la-ipa.tom.ar",1,"$2a$10$cj6AdR3sLeyH3RHErziXHOrWGeNjxz8QZ.dVxzziMXyLcS32VuCqS","alien5.jpg"),
("Tino","Laipa","tino@epa-la-ipa.tom.ar",1,"$2a$10$cj6AdR3sLeyH3RHErziXHOrWGeNjxz8QZ.dVxzziMXyLcS32VuCqS","alien2.jpg");


INSERT INTO epa_la_base2.contenido(contenido)
VALUES("473"),
("500");


INSERT INTO epa_la_base2.marcas(nombre)
VALUES("Cheverry"),
("Mil Almas"),
("Antares"),
("Manush"),
("Temple"),
("Peñón del águila"),
("Ortúzar"),
("Blest"),
("Kira"),
("Patagonia"),
("Rock or Bust"),
("Strange"),
("Grupo 2");


INSERT INTO epa_la_base2.tipos(sabor)
VALUES("Ipa"),
("American Ipa"),
("Stout"),
("Porter"),
("Apa"),
("Red"),
("Honey"),
("Golden"),
("Pilsen"),
("Amber Lager"),
("Kolsch");



INSERT into epa_la_base2.productos (nombre,descripcion,abv,ibu,precio,descuento,foto,stock,rating,marcas_idmarca,contenido_idcontenido,tipos_idtipo)
VALUES("Ipa",
"Es una cerveza elaborada a base de maltas pálidas y un toque de maltas caramelo, con fuerte sabor y aroma a lúpulos americanos, espuma blanca persistente, de cuerpo medio y con gran carácter. Ideal para maridar con quesos fuertes y picante.",
4.8,
22,
295,
15,
"ipa.jpg",
100,
7,
1,
1,
1),
("Golden",
"Cerveza dorada. Refrescante y balanceada en sus maltas y amargor de sus lúpulos.",
4.8,
26,
270,
0,
"golden.jpg",
100,
3,
2,
1,
7),
("Atlantica",
"Es una cerveza fácil de tomar, rubia y refrescante. Posee un sutil aroma y sabor frutado.",
5,
18,
300,
0,
"atlantica-01.jpg",
100,
6,
3,
1,
8),
("Apa",
"Amarga, pero muy equilibrada. Exquisita combinación de maltas caramelo con las notas de pomelo del lúpulo cascade. Con esta APA comenzó la historia de Manush. Un amor duradero. Lúpulos: Nugget y Cascade.",
5.4,
34,
300,
0,
"apa.jpg",
100,
9,
4,
1,
5),
("Honey",
"Es una cerveza elaborada con miel orgánica que se agrega en la etapa de maduración, evitando que se transforme en alcohol, resalte el aroma y el sabor. 
Perfectamente balanceada, refrescante, de color dorado y aroma a malta y cítricos.",
5.5,
19,
290,
0,
"miel.jpg",
100,
2,
5,
1,
7),
("Kölsch",
"Delicado balance. Fermentada con levatdura del tipo Ale pero a baja temperatura, lo que aporta un perfil característico con notas a fruta (manzana y pera)",
4.8,
24,
290,
0,
"peñonkolsh.png",
100,
1,
6,
1,
11),
("Poker",
"Cerveza de color ámbar profundo acompañado por una
espuma densa de gran retención. Cuerpo medio alto.
Sabor a maltas caramelo y fuerte carácter a alcohol
y amargor acompañados por un sutil ahumado.
El agregado de bourbon Jack Daniel’s en madurado
da notas a madera y vainilla hacia el final.",
8.53,
51,
350,
20,
"ortuzar.jpeg",
100,
5,
7,
1,
4),
("Ipa",
"La cerveza Blest IPA posee un marcado golpe de lúpulo, de color ámbar-rojizo, aportado por las maltas caramelizadas. Una característica es el aroma cítrico.
Se usan lúpulos nacionales e importados. En el sabor se mezclan notas terrosas, florales y leve a hierbas. Ideal para disfrutar con comidas de sabores fuertes, carnes ahumadas, picadas de sabores intensos.",
6.5,
54,
290,
10,
"blestipa.jpg",
100,
8,
8,
1,
1),
("Sora",
"Una session IPA de color dorado. Amargor suave y delicado en donde se destacan notas a frutas tropicales, pino y ananá.",
4.8,
38,
350,
10,
"kira.jpg",
100,
6,
9,
1,
1),
("Pilsen",
"La cerveza Blest Pilsen es de color dorado claro, además de la malta Pilsen se utiliza trigo, lo cual aporta generación y mantención de espuma. 
Utilizan lúpulos nacionales e importados, que brindan un característico aroma y sabor amargos, de todos modos, predomina el sabor maltoso. Es una cerveza fresca, balanceada, de cuerpo medio en boca.",
5,
10,
350,
30,
"blestpilsen.jpg",
100,
4,
8,
1,
9),
("Amber Lager",
"En la cerveza Patagonia Amber Lager (730ml), encontrarás un suave sabor a caramelo, elaborada con una combinación de 4 maltas, que le dan su característico color ámbar y sabor maltoso Esta cerveza es una combinación de lúpulos patagónicos y un blend de finas maltas que generan su color rojizo, un delicado aroma y un amargor apacible que revela un tostado delicioso.",
5.2,
14,
250,
0,
"2-12.jpg",
100,
3,
10,
1,
10),
("AC DC",
"La cerveza más rockera. Una APA al estilo Angus Young!s",
6,
25,
400,
0,
"adcdbeer.png",
100,
10,
11,
1,
5);






