-- MySQL Script generated by MySQL Workbench
-- Sun Jul 10 18:56:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema epa_la_base2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema epa_la_base2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `epa_la_base2` DEFAULT CHARACTER SET utf8 ;
USE `epa_la_base2` ;

-- -----------------------------------------------------
-- Table `epa_la_base2`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epa_la_base2`.`marcas` (
  `idmarca` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) UNIQUE NOT NULL,
  PRIMARY KEY (`idmarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epa_la_base2`.`contenido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epa_la_base2`.`contenido` (
  `idcontenido` INT NOT NULL AUTO_INCREMENT,
  `contenido` INT UNIQUE NULL,
  PRIMARY KEY (`idcontenido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epa_la_base2`.`tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epa_la_base2`.`tipos` (
  `idtipo` INT NOT NULL AUTO_INCREMENT,
  `sabor` VARCHAR(45) UNIQUE NULL,
  PRIMARY KEY (`idtipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epa_la_base2`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epa_la_base2`.`productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(999) NOT NULL,
  `abv` INT NULL,
  `ibu` INT NULL,
  `precio` INT NOT NULL,
  `descuento` INT NULL,
  `foto` VARCHAR(100) NOT NULL,
  `stock` INT NULL,
  `rating` INT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `marcas_idmarca` INT NOT NULL,
  `contenido_idcontenido` INT NOT NULL,
  `tipos_idtipo` INT NOT NULL,
  PRIMARY KEY (`idProductos`, `marcas_idmarca`, `contenido_idcontenido`, `tipos_idtipo`),
  INDEX `fk_productos_marcas1_idx` (`marcas_idmarca` ASC) ,
  INDEX `fk_productos_contenido1_idx` (`contenido_idcontenido` ASC) ,
  INDEX `fk_productos_tipos1_idx` (`tipos_idtipo` ASC) ,
  CONSTRAINT `fk_productos_marcas1`
    FOREIGN KEY (`marcas_idmarca`)
    REFERENCES `epa_la_base2`.`marcas` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_contenido1`
    FOREIGN KEY (`contenido_idcontenido`)
    REFERENCES `epa_la_base2`.`contenido` (`idcontenido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_tipos1`
    FOREIGN KEY (`tipos_idtipo`)
    REFERENCES `epa_la_base2`.`tipos` (`idtipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epa_la_base2`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epa_la_base2`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) UNIQUE NULL,
  `password` VARCHAR(70) NOT NULL,
  `apellido` VARCHAR(45) NULL,
  `isadmin` TINYINT(1) NOT NULL default 0,
  `foto` VARCHAR(255) NULL,
  `direccion` VARCHAR(255) NULL,
  `codigopostal` INT NULL,
  PRIMARY KEY (`id_usuario`));





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
